# Generated by Django 5.2.15 on 2026-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'constraints': [models.CheckConstraint(condition=models.Q(('saldo_atual__gte', 0)), name='caixa_saldo_atual_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('compra_estoque', 'Compra de Estoque'), ('ajuste_manual', 'Ajuste Manual')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Movimentacao Financeira',
                'verbose_name_plural': 'Movimentacoes Financeiras',
                'ordering': ['-data', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='movimentacao_financeira_valor_nao_negativo')],
            },
        ),
    ]
