# Generated by Django 5.2.15 on 2026-06-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='caixa_unico_id_igual_1'),
        ),
    ]
