# Generated by Django 5.2.15 on 2026-06-28 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_caixa_caixa_unico_id_igual_1'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_financeiras', to='vendas.venda'),
        ),
    ]
