# Generated by Django 5.2.15 on 2026-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_movimentacaofinanceira_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20),
        ),
    ]
