# Generated by Django 5.2.15 on 2026-06-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Virtual',
                'verbose_name_plural': 'Clientes Virtuais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('horario_programado', models.DateTimeField()),
                ('horario_inicio', models.DateTimeField(blank=True, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('desistiu', 'Desistiu')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente_virtual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.clientevirtual')),
            ],
            options={
                'verbose_name': 'Atendimento Virtual',
                'verbose_name_plural': 'Atendimentos Virtuais',
                'ordering': ['horario_programado', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.atendimentovirtual')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_virtuais', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Pedido Virtual',
                'verbose_name_plural': 'Pedidos Virtuais',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='atendimentovirtual',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='atendimento_virtual_valor_total_nao_negativo'),
        ),
    ]
