# Generated by Django 5.2.15 on 2026-06-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrou_fila', 'Entrou na fila'), ('aguardando', 'Aguardando'), ('desistiu', 'Desistiu')], max_length=20)),
                ('mensagem', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='clientes.atendimentovirtual')),
            ],
            options={
                'verbose_name': 'Evento de Cliente',
                'verbose_name_plural': 'Eventos de Clientes',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
