# Generated by Django 5.2.15 on 2026-06-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_eventocliente'),
        ('vendas', '0002_alter_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentovirtual',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_virtual', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='eventocliente',
            name='tipo',
            field=models.CharField(choices=[('entrou_fila', 'Entrou na fila'), ('aguardando', 'Aguardando'), ('atendimento_iniciado', 'Atendimento iniciado'), ('atendido', 'Atendido'), ('desistiu', 'Desistiu')], max_length=20),
        ),
    ]
