# Generated by Django 5.2.15 on 2026-06-29 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_atendimentovirtual_venda_alter_eventocliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentovirtual',
            name='estado_conversa',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('em_negociacao', 'Em Negociacao'), ('adicionando_produtos', 'Adicionando Produtos'), ('finalizando', 'Finalizando'), ('concluido', 'Concluido')], default='iniciado', max_length=24),
        ),
        migrations.CreateModel(
            name='InteracaoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('sistema', 'Sistema'), ('operadora', 'Operadora')], max_length=12)),
                ('acao', models.CharField(choices=[('iniciar', 'Iniciar'), ('sim_temos', 'Sim, temos'), ('nao_temos', 'Nao temos'), ('ver_outros_produtos', 'Ver outros produtos'), ('finalizar_compra', 'Finalizar compra'), ('cancelar_atendimento', 'Cancelar atendimento')], max_length=24)),
                ('mensagem', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interacoes', to='clientes.atendimentovirtual')),
            ],
            options={
                'verbose_name': 'Interacao de Conversa',
                'verbose_name_plural': 'Interacoes de Conversa',
                'ordering': ['data', 'id'],
            },
        ),
    ]
