# Generated by Django 5.2.15 on 2026-06-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='fechado', max_length=10)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='expediente_unico_id_igual_1')],
            },
        ),
    ]
