# Generated by Django 5.2.15 on 2026-06-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_venda', models.CharField(max_length=40, unique=True)),
                ('data', models.DateTimeField()),
                ('tipo_cliente', models.CharField(choices=[('real', 'Real'), ('virtual', 'Virtual')], max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('concluida', 'Concluida'), ('cancelada', 'Cancelada')], max_length=12)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='venda_valor_total_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='item_venda_valor_unitario_nao_negativo'), models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='item_venda_valor_total_nao_negativo')],
            },
        ),
    ]
