# Generated by Django 5.2.15 on 2026-06-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], max_length=12),
        ),
    ]
