# Generated by Django 5.2.15 on 2026-06-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('venda', 'Venda'), ('ajuste_manual', 'Ajuste Manual')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('observacao', models.TextField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Movimentacao de Estoque',
                'verbose_name_plural': 'Movimentacoes de Estoque',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
